default_install_hook_types: [pre-commit, pre-merge-commit, pre-push]
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: format
        name: format with isort and black
        entry: make format
        language: system
        types: [python]

      - id: flake8
        name: lint with flake8
        entry: make lint-flake8
        language: system
        types: [python]

      - id: pylint
        name: lint with pylint
        entry: make lint-pylint
        language: system
        types: [python]
        stages: [push]
