# Model configuration
model:
  learning_rate: 0.05
  loss: "warp"  # Options: warp, bpr, warp-kos, logistic
  no_components: 64
  max_sampled: 20
  random_state: 42

# Training configuration
training:
  num_epochs: 10
  num_threads: 4
  batch_size: 256
  validation_size: 0.20

# Evaluation configuration
evaluation:
  metrics:
    - precision
    - recall
    - ndcg
    - map
  k_values:
    - 5
    - 10
    - 20
  n_folds: 5

# Data generation configuration
data:
  n_users: 1000
  n_items: 5000
  n_interactions: 10000
  random_seed: 42
